engines:
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
  duplication:
    enable: true
    config:
      languages:
        - javascript
ratings:
  paths:
    - src/**/*
exclude_paths:
  - docs/**/*
  - test/**/*
  - gulpfile.js
  - .eslintrc.js